name: e2e-test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Set up Docker cache directory
        run: |
          mkdir -p /tmp/docker-cache

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Build all services in docker-compose.e2e.yaml
        id: build
        run: |
          docker compose -f docker-compose.e2e.yaml \
            build --build-arg BUILDKIT_INLINE_CACHE=1 \

      - name: Save built images
        run: |
          docker save -o /tmp/docker-cache/playwright-web.tar turborepo-template-playwright-web:latest
          docker save -o /tmp/docker-cache/web.tar turborepo-template-web:latest

  run-playwright:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Load built images
        run: |
          docker load -i /tmp/docker-cache/playwright-web.tar
          docker load -i /tmp/docker-cache/web.tar

      - name: Prepare docker external network
        run: |
          docker network create "e2e_network"

      - name: Run E2E tests
        run: |
          docker compose -f docker-compose.e2e.yaml up --exit-code-from playwright-web