name: e2e-test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Save Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ steps.build.outputs.image-tag }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build E2E environment
        id: build
        run: |
          IMAGE_TAG=e2e-${{ github.sha }}
          echo "::set-output name=image-tag::${IMAGE_TAG}"
          docker compose -f docker-compose.e2e.yaml build
          docker images
          docker tag turborepo-template-playwright-web:latest playwright-web:${IMAGE_TAG}

  run-playwright:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ needs.build.outputs.image-tag }}

      - name: Run E2E tests
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image-tag }}
          docker compose -f docker-compose.e2e.yaml up --exit-code-from playwright-web
