name: e2e-test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Build E2E environment
        id: build
        run: |
          docker compose build \
            --cache-from=type=local,src=/tmp/docker-cache \
            --cache-to=type=local,dest=/tmp/docker-cache,mode=max \
            -f docker-compose.e2e.yaml \
            -t turborepo-template-playwright-web:latest

      - name: Save Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}

  run-playwright:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Load Docker image from cache
        run: |
          docker load -i /tmp/docker-cache/playwright-web.tar
          docker load -i /tmp/docker-cache/web.tar

      - name: Prepare docker external network
        run: |
          docker network create "e2e_network"

      - name: Run E2E tests
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image-tag }}
          docker compose -f docker-compose.e2e.yaml up --exit-code-from playwright-web