name: e2e-test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Setup Docker image Caching
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-e2e-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-e2e-

      - name: Load Docker image from tar
        run: |
          if [ -f /tmp/docker-cache/playwright-web.tar ]; then
            docker load -i /tmp/docker-cache/playwright-web.tar
          fi
          if [ -f /tmp/docker-cache/web.tar ]; then
            docker load -i /tmp/docker-cache/web.tar
          fi

      - name: Create cache directory
        run: mkdir -p /tmp/docker-cache

      - name: Build E2E environment
        id: build
        run: |
          docker compose -f docker-compose.e2e.yaml build
          docker save -o /tmp/docker-cache/playwright-web.tar turborepo-template-playwright-web:latest
          docker save -o /tmp/docker-cache/web.tar turborepo-template-web:latest

  run-playwright:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-e2e-${{ github.ref_name }}

      - name: Load Docker image from tar
        run: |
          docker load -i /tmp/docker-cache/playwright-web.tar
          docker load -i /tmp/docker-cache/web.tar

      - name: Prepare docker external network
        run: |
          docker network create "e2e_network"

      - name: Run E2E tests
        run: |
          docker compose -f docker-compose.e2e.yaml up --exit-code-from playwright-web
