name: e2e-test

on:
  push:
    branches:
      - '*'

env:
  DOCKER_BUILDKIT: 1

jobs:
  run-docker-compose-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Docker cache directory exists
        run: mkdir -p /tmp/docker-cache

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: inject environment variables
        run: |
          docker compose -f docker-compose.ci.e2e.yaml convert > docker-compose.e2e.converted.yaml
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Build E2E environment
        id: build
        run: |
          docker compose -f docker-compose.e2e.converted.yaml build

      - name: Prepare docker external network
        run: |
          docker network inspect "e2e_network" >/dev/null 2>&1 || docker network create "e2e_network"

      - name: Run E2E tests
        run: |
          docker compose -f docker-compose.e2e.converted.yaml up --exit-code-from playwright-web

      - name: Copy E2E report from container
        run: |
          CONTAINER_ID=$(docker ps -aqf "name=turborepo-template-playwright-web")
          if [ -n "$CONTAINER_ID" ]; then
            docker cp $CONTAINER_ID:/app/tools/playwright-web/test-results/junit.xml ./junit.xml
          else
            echo "No container found for playwright-web"
            exit 1
          fi

      - name: Upload E2E report
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: ./junit.xml
