name: e2e-test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Build all services in docker-compose.e2e.yaml
        id: build
        run: |
          mkdir -p /tmp/docker-cache
          docker compose build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -f docker-compose.e2e.yaml

      - name: Save Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}

  run-playwright:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      - name: Prepare docker external network
        run: |
          docker network create "e2e_network"

      - name: Run E2E tests
        run: |
          docker compose -f docker-compose.e2e.yaml up --exit-code-from playwright-web