name: install-and-build

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Cache turbo task output
        id: cache-turbo
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: turbo-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}-${{ github.sha }}
          restore-keys: |
            turbo-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}-
            turbo-cache-${{ runner.os }}-
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
            configs/*/node_modules
            shared/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: pnpm install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs: install
    outputs:
      dist-cache-key: ${{ steps.cache-dist.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: turbo-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}-${{ github.sha }}
          restore-keys: |
            turbo-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}-
            turbo-cache-${{ runner.os }}-
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
            configs/*/node_modules
            shared/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}
      - name: Cache dist directories
        id: cache-dist
        uses: actions/cache@v4
        with:
          path: |
            apps/*/.next
            !apps/*/.next/cache
            apps/*/storybook-static
            packages/*/dist
            configs/*/dist
            shared/*/dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-
      - run: |
          TURBO_LOG_LEVEL=debug pnpm run build --summarize > turbo-build-stdout.log
          cp $(cat turbo-build-stdout.log | tail -n 2 | head -n 1 | sed 's/^Summary:    //' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//') ./turbo-build-summarize.log
      - name: Upload turbo summarize log
        uses: actions/upload-artifact@v4
        with:
          name: turbo-build-summarize
          path: |
            turbo-build-stdout.log
            turbo-build-summarize.log
