name: install-and-build

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Cache turbo task output
        id: cache-turbo
        uses: actions/cache@v4
        with:
          # Consolidating multiple turbo cache paths into a single '.turbo' entry simplifies cache management
          # and aligns with turbo's caching mechanism.
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
            configs/*/node_modules
            shared/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: pnpm install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs: install
    outputs:
      dist-cache-key: ${{ steps.cache-dist.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
            configs/*/node_modules
            shared/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}
      - name: Cache dist directories
        id: cache-dist
        uses: actions/cache@v3
        with:
          path: |
            apps/*/.next
            !apps/*/.next/cache
            apps/*/storybook-static
            packages/*/dist
            configs/*/dist
            shared/*/dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-
      - run: pnpm run build
