name: lighthouse-test

on:
  push:
    branches:
      - '*'

jobs:
  run-docker-compose-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: inject LHCI_GITHUB_APP_TOKEN
        run: |
          docker compose -f docker-compose.lighthouse.yaml convert > docker-compose.lighthouse.converted.yaml
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Build Lighthouse environment
        id: build
        run: |
          docker compose -f docker-compose.lighthouse.converted.yaml build

      - name: Prepare docker external network
        run: |
          docker network inspect "lighthouse_network" >/dev/null 2>&1 || docker network create "lighthouse_network"

      - name: Run Lighthouse tests
        run: |
          docker compose -f docker-compose.lighthouse.converted.yaml up --exit-code-from lighthouse-runner
