name: lighthouse-test

on:
  push:
    branches:
      - '*'

env:
  DOCKER_BUILDKIT: 1

jobs:
  run-docker-compose-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Docker cache directory exists
        run: mkdir -p /tmp/docker-cache

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Pull cached images
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/web:cache || echo "No cached image found for web"
          docker pull ghcr.io/${{ github.repository_owner }}/lighthouse-runner:cache || echo "No cached image found for lighthouse-runner"

      - name: inject environment variables
        run: |
          docker compose -f docker-compose.lighthouse.yaml convert > docker-compose.lighthouse.converted.yaml
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Build Lighthouse environment
        id: build
        run: |
          docker compose -f docker-compose.lighthouse.converted.yaml build

      - name: Push cached images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/web:cache
          docker push ghcr.io/${{ github.repository_owner }}/lighthouse-runner:cache

      - name: Prepare docker external network
        run: |
          docker network inspect "lighthouse_network" >/dev/null 2>&1 || docker network create "lighthouse_network"

      - name: Run Lighthouse tests
        run: |
          docker compose -f docker-compose.lighthouse.converted.yaml up --exit-code-from lighthouse-runner
