name: storybook-test

on:
  push:
    branches:
      - '*'

env:
  DOCKER_BUILDKIT: 1

jobs:
  run-docker-compose-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Docker cache directory exists
        run: mkdir -p /tmp/docker-cache

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Pull cached images
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/storybook:cache || echo "No cached image found for storybook"
          docker pull ghcr.io/${{ github.repository_owner }}/storybook-test-runner:cache || echo "No cached image found for storybook-test-runner"

      - name: Build Storybook test environment
        id: build
        run: |
          docker compose -f docker-compose.storybook.yaml build \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository_owner }}/storybook:cache \
            --cache-to=type=registry,ref=ghcr.io/${{ github.repository_owner }}/storybook:cache,mode=max \
            --cache-from=type=registry,ref=ghcr.io/${{ github.repository_owner }}/storybook-test-runner:cache \
            --cache-to=type=registry,ref=ghcr.io/${{ github.repository_owner }}/storybook-test-runner:cache,mode=max

      - name: Push cached images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/storybook:cache
          docker push ghcr.io/${{ github.repository_owner }}/storybook-test-runner:cache

      - name: Prepare docker external network
        run: |
          docker network inspect "storybook_network" >/dev/null 2>&1 || docker network create "storybook_network"

      - name: Run Storybook tests
        run: |
          docker compose -f docker-compose.storybook.yaml up --exit-code-from storybook-test-runner

      - name: Copy Storybook report from container
        run: |
          CONTAINER_ID=$(docker ps -aqf "name=turborepo-template-storybook-test-runner")
          if [ -n "$CONTAINER_ID" ]; then
            docker cp $CONTAINER_ID:/app/apps/frontend-workshop/test-results/a11y-audit ./
          else
            echo "No container found for storybook-test-runner"
            exit 1
          fi

      - name: Upload Storybook A11y report
        uses: actions/upload-artifact@v4
        with:
          name: storybook-a11y-report
          path: ./a11y-audit
