name: unit-test

on:
  push:
    branches:
      - '*'

jobs:
  wait-for-install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for install-and-build workflow
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo,
            });

            const workflowName = "install-and-build";
            const workflow = workflows.data.workflows.find(w => w.name === workflowName);
            if (!workflow) {
              throw new Error("Workflow 'install-and-build' not found");
            }
            const workflowId = workflow.id;

            let isWorkflowCompleted = false;
            do {
              const completedRuns = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflowId,
                status: "completed",
              });
            
              if (completedRuns.data.total_count === 0) {
                console.log("Waiting for install-and-build workflow to start...");
                await new Promise((resolve) => setTimeout(resolve, 30000)); // 30초 대기
                continue;
              }
            
              const latestRun = completedRuns.data.workflow_runs[0];
              if (latestRun.conclusion === "success") {
                isWorkflowCompleted = true;
              } else if (latestRun.conclusion === "failure" || latestRun.conclusion === "cancelled") {
                throw new Error(
                  `The latest 'install-and-build' workflow run did not succeed. Conclusion: ${latestRun.conclusion}`
                );
              } else {
                console.log("Waiting for install-and-build workflow to complete...");
                await new Promise((resolve) => setTimeout(resolve, 30000)); // 30초 대기
              }
            } while (!isWorkflowCompleted);

            console.log("install-and-build workflow completed.");
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: [wait-for-install-and-build]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Restore turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Restore dist cache
        uses: actions/cache@v3
        with:
          path: |
            packages/*/dist
          key: ${{ runner.os }}-dist-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm run test
      - run: pnpm run merge-json-reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: packages/vitest-config/coverage/merged