name: unit-test

on:
  workflow_run:
    workflows:
      - install-and-build
    types:
      - completed

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            apps/*/.turbo
            tools/*/.turbo
            packages/*/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Restore dist cache
        uses: actions/cache@v3
        with:
          path: |
            apps/*/.next
            !apps/*/.next/cache
            apps/*/storybook-static
            packages/*/dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
      - run: pnpm run test
      - run: pnpm run merge-json-reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: packages/vitest-config/coverage/merged