name: unit-test

on:
  push:
    branches:
      - '*'

jobs:
  trigger-install-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Trigger install-and-build workflow
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const workflowName = "install-and-build";

            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo,
            });

            const workflow = workflows.data.workflows.find(w => w.name === workflowName);
            if (!workflow) {
              throw new Error(`Workflow '${workflowName}' not found`);
            }

            const response = await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow.id,
              ref: context.ref,
            });

            console.log(`Triggered workflow_dispatch for '${workflowName}'`, response);

  wait-for-install-and-build:
    runs-on: ubuntu-latest
    needs: [trigger-install-and-build]
    steps:
      - name: Wait for install-and-build workflow
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo,
            });

            const workflowName = "install-and-build";
            const workflow = workflows.data.workflows.find(w => w.name === workflowName);
            if (!workflow) {
              throw new Error("Workflow 'install-and-build' not found");
            }
            const workflowId = workflow.id;

            let isWorkflowCompleted = false;
            do {
              const allRuns = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflowId,
              });
            
              if (allRuns.data.total_count === 0) {
                console.log("Waiting for install-and-build workflow to start...");
                await new Promise((resolve) => setTimeout(resolve, 30000)); // 30초 대기
                continue;
              }
            
              const latestRun = allRuns.data.workflow_runs[0];
              if (!latestRun?.conclusion) continue;
            
              if (latestRun.conclusion === "success") {
                isWorkflowCompleted = true;
              } else if (latestRun.conclusion === "failure" || latestRun.conclusion === "cancelled") {
                throw new Error(
                  `The latest 'install-and-build' workflow run did not succeed. Conclusion: ${latestRun.conclusion}`
                );
              } else {
                console.log("Waiting for install-and-build workflow to complete...");
                await new Promise((resolve) => setTimeout(resolve, 30000)); // 30초 대기
              }
            } while (!isWorkflowCompleted);

            console.log("install-and-build workflow completed.");
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: [wait-for-install-and-build]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            tools/*/node_modules
            packages/*/node_modules
            configs/*/node_modules
            shared/*/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml', '**/pnpm-workspace.yaml') }}
      - name: Restore dist cache
        uses: actions/cache@v4
        with:
          path: |
            apps/*/.next
            !apps/*/.next/cache
            apps/*/storybook-static
            packages/*/dist
            configs/*/dist
            shared/*/dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
      - name: Restore unit test cache
        uses: actions/cache@v4
        with:
          path: |
            apps/*/coverage.json
            tools/*/coverage.json
            packages/*/coverage.json
            configs/*/coverage.json
            shared/*/coverage.json
          key: ${{ runner.os }}-unittest-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-unittest-
      - run: pnpm run test
      - run: pnpm run merge-json-reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: configs/vitest-config/coverage/merged